aws-containers/retail-store-sample-app

- deploy/kubernetes/kustomize/base/checkout/configMap.yaml
In Kubernetes checkout deployment should use proper orders endpoint, currently it is defaulting to stubbed behavior.
> Fix Orders service endpoint used by Checkout service in Kubernetes

- terraform/lib/dependencies/catalog_rds.tf
- terraform/lib/dependencies/dynamodb.tf
- terraform/lib/dependencies/elasticache.tf
- terraform/lib/dependencies/mq.tf
- terraform/lib/dependencies/orders_rds.tf
- terraform/lib/dependencies/outputs.tf
- terraform/lib/dependencies/rds.tf
- terraform/lib/dependencies/variables.tf
Adding the initial resources for the dependencies. Terraform apply can be ran from the `standalone` directory and the VPC module will be used to create the VPC and the required subnets.
> chore: Dependencies - RDS/MQ/ElastiCache/DDB

- .github/workflows/e2e-test.yml
- scripts/e2e-kind.sh
- scripts/e2e.sh
Currently there are end-to-end tests for Docker that builds the container images, creates the container with Docker Compose and then runs the e2e test suite. This PR introduces the same mechanism for Kubernetes using kind.
> chore: Add e2e tests for Kubernetes using kind

- deploy/kubernetes/charts/catalog/templates/mysql-statefulset.yaml
- deploy/kubernetes/charts/catalog/values.yaml
- deploy/kubernetes/charts/orders/templates/mysql-statefulset.yaml
- deploy/kubernetes/charts/orders/templates/rabbitmq-statefulset.yaml
- deploy/kubernetes/charts/orders/values.yaml
> feat: Add persist option for MySQL and RabbitMQ

- src/checkout/README.md
- src/checkout/src/checkout/checkout.module.ts
- src/checkout/src/checkout/shipping/MockShippingService.ts
- src/checkout/src/config/configuration.ts
Adds the parameter `SHIPPING_NAME_PREFIX` to the checkout service which will prefix all shipping option names with the provided string. This is useful to illustrate backend A/B scenarios without building a separate image.
The parameter is empty by default.
> feat: Add parameter to checkout service to add prefix to shipping option names

- src/e2e/package.json
There are been repeated GitHub API throttling in CI jobs which seems to be related to the gecko driver. This is being disabled to make the tests more stable.
> fix: Disable firefox/gecko in webdriver manager

- src/catalog/repository/mysql_repository.go
Related to #154 
This misleading error would occur when the catalog service starts:
```
catalog-catalog-1     | 2023/02/23 14:50:40 Error: Failed to apply migration <nil>
```
This PR improves the handling of the error response from the DB migration to remove this error.
> fix: Better handling of catalog db migration error value

- deploy/kubernetes/charts/assets/templates/tests/test-connection.yaml
- deploy/kubernetes/charts/catalog/values.yaml
- deploy/kubernetes/charts/orders/values.yaml
PVC persistence should be turned off by default in the helm charts so that it functions on Kubernetes clusters with no CSI driver.
> fix: Disable PVC persistence by default in helm charts

- README.md
- dist/kubernetes/deploy.yaml
- scripts/patch-image-tag.sh
Kubernetes dist manifest should not include test connection pods. Also updates it to include a load balancer service, with README updated to reflect new naming.
> fix: Exclude test pods from Kubernetes dist manifest

- src/ui/src/main/resources/templates/detail.html
- src/ui/src/main/resources/templates/fragments/checkout.html
- src/ui/src/main/resources/templates/fragments/layout.html
- src/ui/src/main/resources/templates/fragments/product_card.html
> fix: Remediate Thymeleaf deprecation warnings

- deploy/docker-compose/docker-compose.yml
Increases the UI component request from 256M to 512M since the former was causing crashes when running the load generator.
> fix: Increase UI component memory request in docker compose

- src/orders/src/main/java/com/amazon/sample/orders/metrics/OrdersMetrics.java
- src/orders/src/test/java/com/amazon/sample/orders/metrics/OrdersMetricsTest.java
Orders unit test were regularly failing with:
```
Error:    OrdersMetricsTest.testCreateCounterAndIncrement:102 
expected: 600.0
but was: NaN
```
This shows the reference to the metric value has not being maintained properly.
Resolved this by changing how gauge is created and integer value is referenced.
> fix: Prevent orders metrics NaN with proper reference

- images/go/Dockerfile
- images/java17/Dockerfile
- images/nodejs/Dockerfile
- src/assets/Dockerfile
- src/load-generator/Dockerfile
We get a few advantages with moving to Amazon Linux 2023, the most notable being that we get to use more packages provided by the OS rather than downloading some. For example, we can use the node and npm binaries from the RPM packages in AL2023.
We also take the opportunity to move to pulling base images from ECR rather than DockerHub.
Using curl rather than wget also means we don't need to add wget to the list of packages we're installing in the container, thus keeping things nice and minimal.
> build: Move images to be based on Amazon Linux 2023

- src/ui/src/main/resources/templates/fragments/error.html
Corrected error message from "Opps! Sorry." to "Oops! Sorry."
> style: Fix spelling error on Oops

- deploy/terraform/lib/dependencies/elasticache.tf
- deploy/terraform/lib/eks/eks.tf
- deploy/terraform/lib/vpc/vpc.tf
Updates several Terraform modules for compatibility with the AWS v5 provider. Also bumps the version of EKS blueprints for Terraform module version.
> chore: Terraform AWS provider v5 updates

- src/cart/pom.xml
- src/cart/src/main/java/com/amazon/sample/carts/configuration/DynamoDBConfiguration.java
- src/cart/src/main/java/com/amazon/sample/carts/configuration/DynamoDBProperties.java
- src/cart/src/main/java/com/amazon/sample/carts/repositories/dynamo/entities/DynamoItemEntity.java
- src/cart/src/main/java/com/amazon/sample/carts/services/DynamoDBCartService.java
- src/cart/src/test/java/com/amazon/sample/carts/services/DynamoDBCartServiceTests.java
In order for the new EKS pod identity feature to work the carts service needed to be migrated to the AWS SDK for Java v2.
> chore: Migrated carts service to AWS SDK for Java v2

- deploy/terraform/lib/dependencies/mq.tf
- deploy/terraform/lib/dependencies/outputs.tf
Migrate the RabbitMQ TF configuration to the base AWS provider to make the configuration less opaque and easier to maintain.
> chore: Migrate RabbitMQ broker to base TF provider

- deploy/kubernetes/charts/orders/templates/rabbitmq-secret.yaml
Environment variable for RabbitMQ username should be `SPRING_RABBITMQ_USERNAME`
> fix: Fix RabbitMQ username environment variable

- deploy/terraform/apprunner/main.tf
- deploy/terraform/apprunner/variables.tf
- deploy/terraform/eks/default/kubernetes.tf
- deploy/terraform/eks/default/values/assets.yaml
- deploy/terraform/eks/default/values/carts.yaml
- deploy/terraform/eks/default/values/catalog.yaml
- deploy/terraform/eks/default/values/checkout.yaml
- deploy/terraform/eks/default/values/orders.yaml
- deploy/terraform/eks/default/values/ui.yaml
- deploy/terraform/eks/default/variables.tf
- deploy/terraform/eks/minimal/variables.tf
- deploy/terraform/lib/apprunner/assets.tf
- deploy/terraform/lib/apprunner/carts.tf
- deploy/terraform/lib/apprunner/catalog.tf
- deploy/terraform/lib/apprunner/checkout.tf
- deploy/terraform/lib/apprunner/common.tf
- deploy/terraform/lib/apprunner/orders.tf
- deploy/terraform/lib/apprunner/ui.tf
- deploy/terraform/lib/apprunner/variables.tf
- deploy/terraform/lib/eks/eks.tf
- deploy/terraform/lib/images/main.tf
- deploy/terraform/lib/images/outputs.tf
This PR adds the ability to configure custom images for the Terraform modules available in the repository. For example you could publish custom images to a private ECR repository like so:
```bash
scripts/build-image.sh -r 1234567890.dkr.ecr.us-west-2.amazonaws.com/aws-containers --tag custom --push
```
And reference these in Terraform by creating a `tfvars` file that has the following:
```hcl
container_image_overrides = {
default_repository = "1234567890.dkr.ecr.us-west-2.amazonaws.com/aws-containers"
default_tag        = "custom"
}
```
> feat: Added configurable container image variables to Terraform

- deploy/terraform/eks/default/main.tf
- deploy/terraform/eks/minimal/main.tf
Upgrades the default version of EKS used in the Terraform configuration from 1.24 to 1.28
> chore: Bump EKS version in Terraform to 1.28

- src/orders/src/main/java/com/amazon/sample/orders/web/OrderController.java
- src/ui/pom.xml
- src/ui/src/main/java/com/amazon/sample/ui/services/checkout/CheckoutService.java
- src/ui/src/main/java/com/amazon/sample/ui/web/BaseController.java
- src/ui/src/main/java/com/amazon/sample/ui/web/CatalogImageController.java
- src/ui/src/main/java/com/amazon/sample/ui/web/ProxyController.java
This PR adds an endpoint `/proxy` to the UI service that forwards `GET` requests to the downstream service, allowing better accessibility of these services without exposing them with their own load balancers/ports.
For example sending this request to the UI service:
```
curl localhost:8888/proxy/catalogue
```
Will call `/catalogue' on the catalog service.
If an `ENDPOINT_` entry has not been configured for the relevant service the proxy endpoint will return a 404 with an error message.
> feat: Added proxy endpoint to UI service

- README.md
#444 
Adjusted the `up` command after the file is defined so that the command executes successfully. Huzzah for small differences between docker-compose and docker compose.
> fix: Updated compose syntax specifying file

- src/orders/README.md
- src/orders/pom.xml
- src/orders/src/main/java/com/amazon/sample/orders/config/messaging/InMemoryMessagingConfig.java
- src/orders/src/main/java/com/amazon/sample/orders/config/messaging/RabbitMQMessagingConfig.java
- src/orders/src/main/java/com/amazon/sample/orders/config/messaging/SqsMessagingConfig.java
- src/orders/src/main/java/com/amazon/sample/orders/messaging/sqs/SqsMessagingProvider.java
- src/orders/src/main/resources/application-default.yml
- src/orders/src/main/resources/application-rabbitmq.yml
- src/orders/src/main/resources/application.yml
- src/orders/src/test/java/com/amazon/sample/orders/OrdersApplicationTests.java
- src/orders/src/test/java/com/amazon/sample/orders/services/OrderServicePostgresTests.java
This PR adds an implementation of the messaging abstraction in the orders service that publishes messages to Amazon SQS. See the orders service README for more information.
> feat: Added SQS implementation for orders events

- deploy/docker-compose/docker-compose.yml
- deploy/terraform/lib/apprunner/orders.tf
- deploy/terraform/lib/ecs/orders.tf
- src/orders/README.md
- src/orders/docker-compose.yml
- src/orders/src/main/java/com/amazon/sample/orders/config/messaging/InMemoryMessagingConfig.java
- src/orders/src/main/java/com/amazon/sample/orders/config/messaging/RabbitMQMessagingConfig.java
- src/orders/src/main/java/com/amazon/sample/orders/config/messaging/SqsMessagingConfig.java
- src/orders/src/main/java/com/amazon/sample/orders/messaging/inmemory/InMemoryMessagingProvider.java
- src/orders/src/main/java/com/amazon/sample/orders/web/OrderController.java
- src/orders/src/main/java/com/amazon/sample/orders/web/payload/Order.java
- src/orders/src/main/java/com/amazon/sample/orders/web/payload/OrderMapper.java
- src/orders/src/main/resources/application.yml
- src/orders/src/test/java/com/amazon/sample/orders/OrdersApplicationTests.java
- src/orders/src/test/java/com/amazon/sample/orders/services/OrderServicePostgresTests.java
This PR moves configuring the orders service messaging functionality away from using Spring profiles and to a more explicit configuration style.
Currently to activate RabbitMQ you need to set `SPRING_ACTIVE_PROFILES=rabbitmq`. This is very tied to Spring Boot.
Now you can set `RETAIL_ORDERS_MESSAGING_PROVIDER` to either `in-memory`, `sqs` or `rabbitmq`.
> feat: Re-worked orders messaging configuration

- src/ui/src/main/java/com/amazon/sample/ui/services/catalog/MockCatalogService.java
Makes the product names and descriptions generated by the mock catalog service in the UI service a bit tidied. Instead of `product11` the generated name would be `Sample Product 11`.
> fix: Improved mock catalog product names and descriptions

- deploy/terraform/apprunner/README.md
- deploy/terraform/lib/apprunner/assets.tf
- deploy/terraform/lib/apprunner/carts.tf
- deploy/terraform/lib/apprunner/catalog.tf
- deploy/terraform/lib/apprunner/checkout.tf
- deploy/terraform/lib/apprunner/common.tf
- deploy/terraform/lib/apprunner/orders.tf
- deploy/terraform/lib/apprunner/ui.tf
*Issue #, if available:* N/A
*Description of changes:* The App Runner Terraform was failing to deploy properly with ECR Public images due to providing authentication configuration only suitable for ECR private repositories. This authentication configuration is now passed in conditionally depending on the repository type.
> fix: Properly handle public ECR images in App Runner Terraform

- deploy/kubernetes/charts/orders/templates/configmap.yml
*Issue #, if available:* N/A
The orders helm chart now uses the new setting as of 0.8.0 to enable rabbitmq
> fix: Orders helm chart should enable rabbitmq messaging

- deploy/terraform/lib/eks/adot.tf
- deploy/terraform/lib/eks/variables.tf
Upgrade version of EKS used by Terraform to 1.29
> chore: Upgrade Terraform to use EKS 1.29

- src/ui/README.md
- src/ui/src/main/java/com/amazon/sample/ui/web/UtilityController.java
*Issue #, if available:* Related to #596
Adds two HTTP endpoints to the UI component that are useful for certain demo scenarios:
`/utility/stress/{iterations}` generates CPU load
`/utility/status/{code}` returns an HTTP response with the given HTTP status code
> feat: Added stress and status utility endpoints

- src/checkout/Dockerfile
This PR changes the Dockerfile for the checkout component to use a multi-stage build. This gives more flexibility in the version of `npm` used to build the application without it being package in the final distributed image.
> chore: multi-stage build for checkout

- deploy/terraform/lib/dependencies/mq.tf
Issue #, if available: 665
Description of changes: Update TF resource aws_mq_broker to a supported engine_version. 3.11.16 is current.
> fix: Update aws_mq_broker to a supported engine_version

- src/orders/Dockerfile
- src/ui/Dockerfile
Amazon Linux 2023 [now have curl-minimal installed by default](https://docs.aws.amazon.com/linux/al2023/ug/curl-minimal.html), which don't support scheme other than http ones.
As the Network Policies modules workshop leverage on it: 
https://eksworkshop.com/docs/networking/vpc-cni/network-policies/egress & https://eksworkshop.com/docs/networking/vpc-cni/network-policies/ingress
swapping to curl-full to have `telnet://` supported.
Other alternatives are using `/dev/tcp` or `netcat` for doing connectivity tests.
Note: the test of the workshop module is not failing as the [command tested expect to fail](https://github.com/aws-samples/eks-workshop-v2/blob/main/website/docs/networking/vpc-cni/network-policies/egress.md?plain=1#L65).
By …
> fix: Enable full functionality curl for ui & orders

- src/ui/src/main/java/com/amazon/sample/ui/web/HomeController.java
Originally accessing the index page `/` of the UI component would cause an HTTP redirect to `/home`. Functionally this was fine but causes some confusion when deploying the application where things like health checks expect a 200 response.
This change causes the index page to just render the same response as `/home` without the redirect.
> feat: UI home page renders instead of redirect

- deploy/kubernetes/charts/carts/values.yaml
- src/cart/docker-compose.yml
- src/cart/src/test/java/com/amazon/sample/carts/services/DynamoDBCartServiceTests.java
Sets all the DynamoDB local image versions to 1.20.0 for consistency. This also ensures that all instances use a version that is arm64 compatible.
> fix: Use consistent DynamoDB local image version

- src/ui/README.md
- src/ui/src/main/java/com/amazon/sample/ui/web/UtilityController.java
Closes: #596 
* `GET /headers` Print the heads of the inbound request
* `GET /panic` Shutdown the application with an error code
* `POST /echo` Write back the payload sent to it
* `POST /store` Write the payload to a file and return a hash
* `GET /store/{hash}` Return the payload from the file system previously stored
My tests:
```
$ curl localhost:8080/utility/headers
{"Host":["localhost:8080"],"User-Agent":["curl/8.7.1"],"Accept":["*/*"],"X-Session-ID":["ac60f659-0b4e-4d49-9b2a-5f6fbcf8c250"]}
$ curl --include localhost:8080/utility/panic
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain;charset=UTF-8
Content-Length: 16
set-cookie: SESSIONID=ff033cf5-08f6-4f6c-b4c9-4fb89f9b9fdd
Shutting down...
$ curl localhost:8080/utility/echo -X POST -H "Content-Type: application/json" -d …
```
> feat: Add headers, panic, echo and store utilities

- src/ui/src/main/java/com/amazon/sample/ui/services/carts/model/Cart.java
Closes: #751 
The `removeIf` method handles the safe removal of elements, which in this case checks if the item ID matches the one we want to remove.
Without this, removing the last element result in `ConcurrentModificationException`.
> fix: Safely remove cart items

- src/catalog/repository/repository.go
Catalog service logs SQL statements when running in-memory database mode
Removes it
> fix: Remove catalog in-memory db logging

- src/orders/chart/templates/rabbitmq-secret.yaml
*Issue #, if available:* Fixes #893
Updates the orders Helm chart to use the correct username and password variables for RabbitMQ
> fix: Use correct RabbitMQ credential field names

- terraform/ecs/default/variables.tf
- terraform/lib/ecs/service/ecs.tf
None
In the ECS deployment, these changes made the container names unique so that they show up with service specific names in cloudwatch logs.
> fix: Improved CW Logging for ECS default deployment
