- .github/workflows/e2e-test.yml
- deploy/docker-compose/.env
- deploy/docker-compose/Tiltfile
- deploy/docker-compose/docker-compose.yml
- deploy/kubernetes/kustomize/base/assets/deployment.yaml
- deploy/kubernetes/kustomize/base/assets/namespace.yaml
- deploy/kubernetes/kustomize/base/carts/deployment-db.yaml
- deploy/kubernetes/kustomize/base/carts/deployment.yaml
- deploy/kubernetes/kustomize/base/carts/namespace.yaml
- deploy/kubernetes/kustomize/base/catalog/deployment-mysql.yaml
- deploy/kubernetes/kustomize/base/catalog/deployment.yaml
- deploy/kubernetes/kustomize/base/catalog/namespace.yaml
- deploy/kubernetes/kustomize/base/checkout/deployment-redis.yaml
- deploy/kubernetes/kustomize/base/checkout/deployment.yaml
- deploy/kubernetes/kustomize/base/checkout/namespace.yaml
- deploy/kubernetes/kustomize/base/other/namespace.yaml
- deploy/kubernetes/kustomize/base/ui/deployment.yaml
- deploy/kubernetes/kustomize/base/ui/namespace.yaml
- deploy/kubernetes/kustomize/overlays/published-images/kustomization.yaml
- scripts/build-image.sh
- src/e2e/scripts/run-docker.sh
Updated docker-compose and kubernetes manifests to reference proper images for releases to be cut
> chore: Releasable manifests

- src/catalog/README.md
- src/catalog/config/config.go
- src/catalog/repository/mysql_repository.go
Resolves #93 
Added `DB_CONNECT_TIMEOUT` parameter to catalog service to control connection timeout. Defaults to 5 seconds.
> feat: Added parameter to control catalog database connect timeout

- images/nodejs/Dockerfile
Addressing https://github.com/aws-containers/retail-store-sample-app/issues/42
> feat: Changing user to non-root user in nodejs Dockerfile

- terraform/apprunner/README.md
- terraform/apprunner/main.tf
- terraform/apprunner/output.tf
- terraform/apprunner/providers.tf
- terraform/apprunner/variables.tf
- terraform/lib/apprunner/assets.tf
- terraform/lib/apprunner/carts.tf
- terraform/lib/apprunner/catalog.tf
- terraform/lib/apprunner/checkout.tf
- terraform/lib/apprunner/main.tf
- terraform/lib/apprunner/orders.tf
- terraform/lib/apprunner/outputs.tf
- terraform/lib/apprunner/ui.tf
- terraform/lib/apprunner/variables.tf
- terraform/lib/apprunner/versions.tf
- terraform/lib/apprunner/vpc.tf
- terraform/lib/images/README.md
- terraform/lib/images/generated.tf.json
- terraform/lib/images/main.tf
- terraform/lib/images/outputs.tf
- terraform/lib/images/variables.tf
Addresses #91 
Adds an initial implementation of the application running on AWS App Runner using Terraform. Each application components runs as its own AR service and components communicate over VPC networking.
> feat: Terraform implementation for AWS App Runner

- terraform/lib/apprunner/catalog.tf
- terraform/lib/apprunner/checkout.tf
- terraform/lib/apprunner/common.tf
- terraform/lib/apprunner/orders.tf
- terraform/lib/apprunner/ui.tf
- terraform/lib/apprunner/versions.tf
The initial version of the Terraform for the App Runner sample used plain text environment variables for credentials etc. This change migrates to use the AR secrets manager integration for sensitive environment variables.
> feat: Updated App Runner sample to use secrets manager integration

- deploy/kubernetes/kustomize/components/istio/kustomization.yaml
- deploy/kubernetes/kustomize/components/istio/namespace-patch.yaml
- deploy/kubernetes/kustomize/components/istio/virtual-gateway.yaml
- deploy/kubernetes/kustomize/components/istio/virtual-service.yaml
- deploy/kubernetes/kustomize/recipes/istio/kustomization.yaml
- src/cart/README.md
- src/checkout/package-lock.json
- src/checkout/package.json
- terraform/apprunner/README.md
- terraform/eks/main.tf
- terraform/eks/variables.tf
- terraform/lib/dependencies/catalog_rds.tf
- terraform/lib/dependencies/elasticache.tf
- terraform/lib/dependencies/mq.tf
- terraform/lib/dependencies/orders_rds.tf
- terraform/lib/dependencies/variables.tf
- terraform/lib/eks/eks.tf
- terraform/lib/eks/variables.tf
Addressing - https://github.com/aws-containers/retail-store-sample-app/issues/89
> feat: Add support for Istio

- deploy/terraform/lib/dependencies/catalog_rds.tf
- deploy/terraform/lib/dependencies/dynamodb.tf
- deploy/terraform/lib/dependencies/mq.tf
- deploy/terraform/lib/dependencies/orders_rds.tf
Pins Terraform modules that had to versions to those that work.
> fix: Pin Terraform modules to working versions

- .github/workflows/e2e-test.yml
- deploy/docker-compose/.env
- deploy/docker-compose/.gitignore
- deploy/docker-compose/Tiltfile
- deploy/docker-compose/docker-compose.yml
- deploy/docker-compose/scripts/generate_password.sh
- scripts/build-image.sh
This PR renames the images used by the dev docker-compose file and updates the respective Tiltfile so its more usable and consistent with the Kubernetes version.
> chore: Reworked compose file and its Tilt implementation

- src/orders/README.md
Add initial documentation for the orders service including its configuration parameters.
> chore: Added initial README for orders service

- deploy/docker-compose/docker-compose.yml
- src/load-generator/Dockerfile
- src/load-generator/README.md
- src/load-generator/helpers.js
- src/load-generator/package-lock.json
- src/load-generator/package.json
- src/load-generator/scenario.yml
- src/load-generator/scripts/run.sh
- src/orders/src/main/java/com/amazon/sample/orders/metrics/OrdersMetrics.java
Update the load generator to place orders for random products, which generates more interesting metrics in the order service.
> feat: Load generator random order products

- deploy/kubernetes/charts/assets/templates/_helpers.tpl
- deploy/kubernetes/charts/assets/templates/deployment.yaml
- deploy/kubernetes/charts/carts/templates/_helpers.tpl
- deploy/kubernetes/charts/carts/templates/deployment.yaml
- deploy/kubernetes/charts/catalog/templates/_helpers.tpl
- deploy/kubernetes/charts/catalog/templates/deployment.yaml
- deploy/kubernetes/charts/checkout/templates/_helpers.tpl
- deploy/kubernetes/charts/checkout/templates/deployment.yaml
- deploy/kubernetes/charts/opentelemetry/Chart.yaml
- deploy/kubernetes/charts/opentelemetry/templates/clusterrole.yaml
- deploy/kubernetes/charts/opentelemetry/templates/clusterrolebinding.yaml
- deploy/kubernetes/charts/opentelemetry/templates/collector.yaml
- deploy/kubernetes/charts/opentelemetry/templates/instrumentation.yaml
- deploy/kubernetes/charts/opentelemetry/values.yaml
- deploy/kubernetes/charts/orders/templates/_helpers.tpl
- deploy/kubernetes/charts/orders/templates/deployment.yaml
- deploy/kubernetes/charts/ui/templates/_helpers.tpl
- deploy/kubernetes/charts/ui/templates/deployment.yaml
- deploy/terraform/eks/default/adot-xray.tf
- deploy/terraform/eks/default/kubernetes.tf
- deploy/terraform/eks/default/main.tf
- deploy/terraform/eks/default/values/adot-xray.yaml
- deploy/terraform/eks/default/values/assets.yaml
- deploy/terraform/eks/default/values/catalog.yaml
- deploy/terraform/eks/default/values/checkout.yaml
- deploy/terraform/eks/default/values/orders.yaml
- deploy/terraform/eks/default/values/ui.yaml
- deploy/terraform/eks/default/variables.tf
- deploy/terraform/lib/eks/eks.tf
- deploy/terraform/lib/eks/outputs.tf
chore: update to add Opentelemetry add-on, and conditionally add collector for X-Ray traces
> chore: update to add opentelemetry add-on, collector for X-Ray traces

- src/cart/pom.xml
- src/orders/pom.xml
- src/ui/pom.xml
- src/ui/src/main/java/com/amazon/sample/ui/config/Clients.java
Upgrading to Spring Boot 3.2 required unpinning snakeyaml dependency.
> chore: Upgrade to Spring Boot 3.2

- src/cart/src/main/java/com/amazon/sample/carts/configuration/DynamoDBConfiguration.java
- src/cart/src/main/java/com/amazon/sample/carts/services/DynamoDBCartService.java
Fixing a regression introduced with migration to new AWS SDK.
> fix: Cart service should pick up custom dynamodb table name

- README.md
- deploy/kubernetes/charts/catalog/templates/mysql-statefulset.yaml
- deploy/kubernetes/charts/catalog/values.yaml
- deploy/kubernetes/charts/orders/values.yaml
- deploy/terraform/lib/dependencies/catalog_rds.tf
- src/catalog/docker-compose.yml
- src/catalog/test/main_test.go
*Issue #, if available:* N/A
Upgrades references to MySQL in docker compose, helm charts and Terraform to 8.0
> chore: Upgrade MySQL to 8.0

- .prettierignore
- deploy/docker-compose/Tiltfile
- deploy/kubernetes/Tiltfile
- deploy/kubernetes/charts/carts/templates/tests/test-connection.yaml
- deploy/kubernetes/charts/catalog/templates/tests/test-connection.yaml
- deploy/kubernetes/charts/checkout/templates/tests/test-connection.yaml
- deploy/kubernetes/charts/orders/templates/tests/test-connection.yaml
- deploy/kubernetes/charts/ui/templates/tests/test-connection.yaml
Correct the paths in the Helm tests so they are successful
> fix: Make helm tests work correctly

- .github/workflows/ci-assets.yml
- .github/workflows/ci-cart.yml
- .github/workflows/ci-catalog.yml
- .github/workflows/ci-checkout.yml
- .github/workflows/ci-orders.yml
- .github/workflows/ci-ui.yml
- .github/workflows/e2e-test.yml
- .github/workflows/lint-pr.yaml
- .github/workflows/publish-build.yml
> chore: Scoped down workflow permissions

- .github/workflows/ci-checkout.yml
- src/checkout/Dockerfile
> chore: Upgrade checkout to node v20

- README.md
slight fixes to docker compose setup flow
> fix: update docker-compose instructions

- .github/workflows/publish-build.yml
- scripts/helm_push.sh
Adding scripts to push helm charts to ECR Public
Fixed #587 
Adding Scripts to publish helm charts to ECR Public
> chore: Script to publish Helm charts

- deploy/kubernetes/charts/assets/templates/hpa.yaml
- deploy/kubernetes/charts/carts/templates/hpa.yaml
- deploy/kubernetes/charts/catalog/templates/hpa.yaml
- deploy/kubernetes/charts/checkout/templates/hpa.yaml
- deploy/kubernetes/charts/orders/templates/hpa.yaml
- deploy/kubernetes/charts/ui/templates/hpa.yaml
Updates the HPA manifests in Helm to `v2`
> feat: Upgrade HPA manifests to v2

- deploy/kubernetes/charts/ui/templates/ingress.yaml
Upgrades the Ingress specification in the UI helm chart to v1
> feat: Upgrade helm ingress to v1

- deploy/terraform/eks/default/data.tf
- deploy/terraform/eks/default/main.tf
- deploy/terraform/eks/default/opentelemetry.tf
- deploy/terraform/eks/default/variables.tf
- deploy/terraform/eks/minimal/data.tf
- deploy/terraform/eks/minimal/main.tf
- deploy/terraform/eks/minimal/providers.tf
- deploy/terraform/eks/minimal/variables.tf
- deploy/terraform/lib/eks/adot.tf
- deploy/terraform/lib/eks/data.tf
- deploy/terraform/lib/eks/outputs.tf
- deploy/terraform/lib/eks/variables.tf
- deploy/terraform/lib/eks/versions.tf
Upgrades the Terraform for deploying to EKS to use version 1.30
> feat: Upgrade EKS Terraform to 1.30

- deploy/kubernetes/charts/app/Chart.yaml
- deploy/kubernetes/charts/app/values.yaml
- deploy/kubernetes/charts/assets/Chart.yaml
- deploy/kubernetes/charts/assets/values.yaml
- deploy/kubernetes/charts/carts/Chart.yaml
- deploy/kubernetes/charts/carts/values.yaml
- deploy/kubernetes/charts/catalog/Chart.yaml
- deploy/kubernetes/charts/catalog/values.yaml
- deploy/kubernetes/charts/checkout/Chart.yaml
- deploy/kubernetes/charts/checkout/values.yaml
- deploy/kubernetes/charts/orders/Chart.yaml
- deploy/kubernetes/charts/orders/values.yaml
- deploy/kubernetes/charts/ui/Chart.yaml
- deploy/kubernetes/charts/ui/values.yaml
- deploy/terraform/lib/images/generated.tf.json
- dist/docker-compose/docker-compose.yml
- dist/kubernetes/deploy.yaml
Generate pull request for release
> chore(release): 0.8.4

- README.md
Description of changes: Just a minor edit to conform to English usage.
> docs: Fix typo in main README

- README.md
README mentions mysql, but in reality this is running mariadb
suggesting to add MariaDB to README
> add mariadb

- .github/workflows/e2e-test.yml
- src/load-generator/README.md
- src/load-generator/scenario.yml
- src/load-generator/scripts/run-test.sh
Fixes the URL used in the load generator scenario for the final checkout submission.
Also updates load generator tests to check for 404 errors and encapsulates the test steps in a script.
> fix: Fix load generator not completing orders

- src/orders/README.md
Application is expecting the variables without "POSTGRESQL"
> docs: Update PostgreSQL persistence configuration options
